{
 "title": "AWS ECS Clusters",
 "tags": [ "ecs" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Container Instance Count per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "ContainerInstanceCount",
     "namespace": "ECS/ContainerInsights",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service Count per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "ServiceCount",
     "namespace": "ECS/ContainerInsights",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Task Count per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "TaskCount",
     "namespace": "ECS/ContainerInsights",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Deployment Count per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "DeploymentCount",
     "namespace": "ECS/ContainerInsights",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU Utilized",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Memory Utilized",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "NetworkRxBytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "NetworkTxBytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}