{
 "title": "AWS Fargate Golden Signals",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pending tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(aws_ecs_containerinsights_pending_task_count_average)"
    }
   ]
  },
  {
   "title": "Running tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(aws_ecs_containerinsights_running_task_count_average)"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg by (dimension_ServiceName)(aws_ecs_containerinsights_cpu_utilized_average / aws_ecs_containerinsights_cpu_reserved_average)",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "avg by (dimension_ServiceName)(aws_ecs_containerinsights_memory_utilized_average / aws_ecs_containerinsights_memory_reserved_average)",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Desired tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "targets": [
    {
     "expr": "sum(aws_ecs_containerinsights_desired_task_count_average)"
    }
   ]
  },
  {
   "title": "Task by Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_ServiceName)(aws_ecs_containerinsights_running_task_count_average)",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (dimension_ServiceName)(aws_ecs_containerinsights_cpu_utilized_average / aws_ecs_containerinsights_cpu_reserved_average)",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (dimension_ServiceName)(aws_ecs_containerinsights_memory_utilized_average / aws_ecs_containerinsights_memory_reserved_average)",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Read / Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_ServiceName)(rate(aws_ecs_containerinsights_storage_read_bytes_average[15m]))",
     "legendFormat": "Storage read service: {{dimension_ServiceName}}"
    },
    {
     "expr": "sum by (dimension_ServiceName)(rate(aws_ecs_containerinsights_storage_write_bytes_average[15m]))",
     "legendFormat": "Storage write service: {{dimension_ServiceName}}"
    }
   ]
  }
 ]
}