{
 "title": "AWS Fargate Cluster Golden Signals",
 "tags": [ "ecs" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project",
    "label": "Project",
    "query": {
     "query": "label_values(aws_ecs_containerinsights_info, tag_Project)"
    }
   },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aws_ecs_containerinsights_container_instance_count_average, dimension_ClusterName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pending tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_ecs_containerinsights_pending_task_count_average{dimension_ClusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Running tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_ecs_containerinsights_running_task_count_average{dimension_ClusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (dimension_ServiceName)(aws_ecs_containerinsights_cpu_utilized_average{dimension_ClusterName=\"$Cluster\"} / aws_ecs_containerinsights_cpu_reserved_average{dimension_ClusterName=\"$Cluster\"})",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (dimension_ServiceName)(aws_ecs_containerinsights_memory_utilized_average{dimension_ClusterName=\"$Cluster\"} / aws_ecs_containerinsights_memory_reserved_average{dimension_ClusterName=\"$Cluster\"})",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Desired tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_ecs_containerinsights_desired_task_count_average{dimension_ClusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Task by Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_ServiceName)(aws_ecs_containerinsights_running_task_count_average{dimension_ClusterName=\"$Cluster\"})",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (dimension_ServiceName)(aws_ecs_containerinsights_cpu_utilized_average{dimension_ClusterName=\"$Cluster\"} / aws_ecs_containerinsights_cpu_reserved_average{dimension_ClusterName=\"$Cluster\"})",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (dimension_ServiceName)(aws_ecs_containerinsights_memory_utilized_average{dimension_ClusterName=\"$Cluster\"} / aws_ecs_containerinsights_memory_reserved_average{dimension_ClusterName=\"$Cluster\"})",
     "legendFormat": "Service: {{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Storage Read / Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_ServiceName)(rate(aws_ecs_containerinsights_storage_read_bytes_average{dimension_ClusterName=\"$Cluster\"}[15m]))",
     "legendFormat": "Storage read service: {{dimension_ServiceName}}"
    },
    {
     "expr": "sum by (dimension_ServiceName)(rate(aws_ecs_containerinsights_storage_write_bytes_average{dimension_ClusterName=\"$Cluster\"}[15m]))",
     "legendFormat": "Storage write service: {{dimension_ServiceName}}"
    }
   ]
  }
 ]
}